# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/16b0bd14-1b07-477d-a20d-982f9467f6df";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "discard=async" "noatime" ];
    };

  fileSystems."/var/lib" =
    {
      device = "/dev/disk/by-uuid/16b0bd14-1b07-477d-a20d-982f9467f6df";
      fsType = "btrfs";
      options = [ "subvol=lib" "compress=zstd" "discard=async" "noatime" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/16b0bd14-1b07-477d-a20d-982f9467f6df";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "discard=async" "noatime" ];
    };

  fileSystems."/nix/store" =
    {
      device = "/dev/disk/by-uuid/16b0bd14-1b07-477d-a20d-982f9467f6df";
      fsType = "btrfs";
      options = [ "subvol=store" "compress=zstd" "discard=async" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0135-7C8C";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/fdedb47c-a370-4005-ac37-1c186e667de0"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
